version: "3.7"
services:
  app:
    container_name: restapiclass
    image: node:18
    volumes:
      - ./src:/projects
    working_dir: /projects
    restart: always
    ports:
      - "727:3000"
    command: sh -c "if [ ! -d /projects/node_modules ]; then npm install; fi && npm run start"